#!/bin/sh
####################################
#        __    ______  ______      #
#       |  |  |  ____||  ____|     #
#       |  |  | | __  | | __       #
#       |  |__| ||_ | | ||_ |      #
#       |_____|\____| |_____|      #
# -------------------------------- #
#   >> https://lucianogg.info      #
####################################
# MODULE: PC INFO (hardware.sh)    #
####################################

#!/bin/sh
####################################
#        __    ______  ______      #
#       |  |  |  ____||  ____|     #
#       |  |  | | __  | | __       #
#       |  |__| ||_ | | ||_ |      #
#       |_____|\____| |_____|      #
# -------------------------------- #
#   >> https://lucianogg.info      #
####################################
# MODULE: hardware.sh              #
####################################

deploy_thermal_monitor()
{
    TOOL_PATH="$REAL_HOME/tempTool.sh"
    LOG_PATH="$REAL_HOME/thermal_monitor.log"

    FREQ_CHOICE=$(zenity --list \
        --title="Standalone Thermal Monitor" \
        --text="Create an independent temperature monitor script (~/tempTool.sh)\nHow often should it collect data?" \
        --width=550 --height=350 \
        --column="ID" --column="Frequency" --column="Cron Expression" \
        --hide-column=1 \
        "1" "Every 15 minutes" "*/15 * * * *" \
        "2" "Every Hour" "0 * * * *" \
        "3" "Twice a Day (12h/00h)" "0 0,12 * * *" \
        "4" "Daily at Midnight" "0 0 * * *" \
        "5" "Disable / Remove Tool" "REMOVE" 2>/dev/null)

    if [ -z "$FREQ_CHOICE" ]; then
        print_info "Thermal Tool setup canceled."
        return 0
    fi

    if [ "$FREQ_CHOICE" = "5" ]; then
        zenity --question --text="This will remove the scheduled task.\nDo you also want to delete the script and the log file?" 2>/dev/null
        if [ $? -eq 0 ]; then
            rm -f "$TOOL_PATH" "$LOG_PATH"
            print_info "Files removed: tempTool.sh and thermal_monitor.log"
        fi

        CURRENT_CRON=$(crontab -u "$REAL_USER" -l 2>/dev/null | grep -v "$TOOL_PATH")
        echo "$CURRENT_CRON" | crontab -u "$REAL_USER" -

        print_success "Thermal monitoring disabled."
        zenity --info --text="Monitor removed successfully." 2>/dev/null
        return 0
    fi

    print_info "Generating standalone script at $TOOL_PATH..."

    cat << 'EOF' > "$TOOL_PATH"
#!/bin/sh
# Independent Thermal Monitoring Tool
# Generated by Linux Master Assistant

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LOG_FILE="$(dirname "$0")/thermal_monitor.log"

{
    echo "========================================"
    echo " Thermal Report: $(date)"
    echo "========================================"

    echo "[CPU]"
    if command -v sensors >/dev/null 2>&1; then
        sensors | grep -v "ALARM" | grep -E 'temp|Core|Package'
    else
        for zone in /sys/class/thermal/thermal_zone*; do
            if [ -f "$zone/temp" ] && [ -f "$zone/type" ]; then
                type=$(cat "$zone/type")
                temp=$(cat "$zone/temp")
                if [ "$temp" -gt 0 ] 2>/dev/null; then
                    echo "$type: $((temp / 1000))°C"
                fi
            fi
        done
    fi

    echo "[GPU]"
    if command -v nvidia-smi >/dev/null 2>&1; then
        echo "NVIDIA: $(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader 2>/dev/null)°C"
    elif command -v rocm-smi >/dev/null 2>&1; then
        rocm-smi -t | grep -i temp
    else
        echo "No dedicated GPU tools detected."
    fi

    echo "[DISKS]"
    if command -v hddtemp >/dev/null 2>&1; then
        hddtemp /dev/sd* /dev/nvme* 2>/dev/null
    elif command -v smartctl >/dev/null 2>&1; then
        for disk in $(lsblk -nd -o NAME | grep -E "^(sd|nvme)"); do
            T=$(smartctl -A "/dev/$disk" 2>/dev/null | grep -iE "Temperature_Celsius|Temperature:|Temperature Sensor" | awk '{print $NF}' | head -n 1)
            [ -n "$T" ] && echo "/dev/$disk: ${T}°C"
        done
    else
        echo "No disk temp tools (hddtemp/smartmontools) detected."
    fi
    echo ""
} >> "$LOG_FILE"
EOF

    chown "$REAL_USER:$REAL_USER" "$TOOL_PATH"
    chmod +x "$TOOL_PATH"

    case "$FREQ_CHOICE" in
        1) EXPR="*/15 * * * *" ;;
        2) EXPR="0 * * * *" ;;
        3) EXPR="0 0,12 * * *" ;;
        4) EXPR="0 0 * * *" ;;
    esac

    print_info "Configuring crontab for $REAL_USER..."
    CURRENT_CRON=$(crontab -u "$REAL_USER" -l 2>/dev/null | grep -v "$TOOL_PATH")
    (echo "$CURRENT_CRON"; echo "$EXPR $TOOL_PATH") | crontab -u "$REAL_USER" -

    touch "$LOG_PATH"
    chown "$REAL_USER:$REAL_USER" "$LOG_PATH"

    print_success "Standalone Thermal Tool generated and scheduled."
    zenity --info --title="Setup Complete" \
        --text="Tool generated at:\n$TOOL_PATH\n\nLogs will be stored at:\n$LOG_PATH\n\nFrequency: $EXPR" 2>/dev/null
}

get_hardware_info()
{
    HW_ACTION=$(zenity --list \
        --title="Hardware Auditor & Monitor" \
        --text="Select an action for hardware reporting and monitoring:" \
        --width=650 --height=450 \
        --column="ID" --column="Action" --column="Description" \
        --hide-column=1 \
        "1" "Core Hardware" "Report: CPU, Memory (RAM), and Network Interfaces." \
        "2" "Storage & Disks" "Report: Mounted partitions, usage, and block devices." \
        "3" "Thermal Sensors" "Report: Current Temperatures for CPU, GPU, and Disks." \
        "4" "Full System Report" "Report: Combines all of the above." \
        "5" "Deploy Thermal Monitor" "Tool: Create a standalone background temp tracker." 2>/dev/null)

    if [ -z "$HW_ACTION" ]; then
        print_info "Hardware Auditor canceled."
        return 0
    fi

    if [ "$HW_ACTION" = "5" ]; then
        deploy_thermal_monitor
        return 0
    fi

    print_info "Gathering selected hardware metrics..."

    HW_REPORT="/tmp/hw_report_$(date +%Y%m%d_%H%M%S).txt"
    echo "============================================================" > "$HW_REPORT"
    echo " HARDWARE & SYSTEM REPORT" >> "$HW_REPORT"
    echo "============================================================" >> "$HW_REPORT"
    echo "Generated on: $(date) by: $REAL_USER" >> "$HW_REPORT"

    do_core()
    {
        echo "" >> "$HW_REPORT"
        echo "--- CPU INFORMATION ---" >> "$HW_REPORT"
        lscpu | grep -E "Model name|Architecture|CPU\(s\):|Thread\(s\) per core|Core\(s\) per socket|CPU MHz|BogoMIPS" >> "$HW_REPORT"

        echo "" >> "$HW_REPORT"
        echo "--- MEMORY (RAM) ---" >> "$HW_REPORT"
        free -h >> "$HW_REPORT"

        echo "" >> "$HW_REPORT"
        echo "--- NETWORK INTERFACES ---" >> "$HW_REPORT"
        ip -br a >> "$HW_REPORT"
    }

    do_storage()
    {
        echo "" >> "$HW_REPORT"
        echo "--- STORAGE & DISK USAGE ---" >> "$HW_REPORT"
        echo "[Mounted Partitions]" >> "$HW_REPORT"
        df -h -T -x tmpfs -x devtmpfs -x squashfs -x efivarfs >> "$HW_REPORT"

        echo "" >> "$HW_REPORT"
        echo "[Block Devices / Physical Drives]" >> "$HW_REPORT"
        lsblk -o NAME,SIZE,TYPE,MOUNTPOINT >> "$HW_REPORT"
    }

    do_thermals()
    {
        echo "" >> "$HW_REPORT"
        echo "--- THERMAL SENSORS ---" >> "$HW_REPORT"

        echo "[CPU & Motherboard]" >> "$HW_REPORT"
        if command -v sensors >/dev/null 2>&1; then
            sensors | grep -v "ALARM" >> "$HW_REPORT"
        else
            echo "(lm-sensors not found. Reading raw kernel sysfs instead)" >> "$HW_REPORT"
            for zone in /sys/class/thermal/thermal_zone*; do
                if [ -f "$zone/temp" ] && [ -f "$zone/type" ]; then
                    type=$(cat "$zone/type")
                    temp=$(cat "$zone/temp")
                    if [ "$temp" -gt 0 ] 2>/dev/null; then
                        temp_c=$((temp / 1000))
                        echo "$type: ${temp_c}°C" >> "$HW_REPORT"
                    fi
                fi
            done
        fi

        echo "" >> "$HW_REPORT"
        echo "[GPU Temperatures]" >> "$HW_REPORT"
        if command -v nvidia-smi >/dev/null 2>&1; then
            NVIDIA_TEMP=$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader 2>/dev/null)
            echo "NVIDIA GPU: ${NVIDIA_TEMP}°C" >> "$HW_REPORT"
        elif command -v rocm-smi >/dev/null 2>&1; then
            rocm-smi -t | grep -i temp >> "$HW_REPORT"
        else
            echo "No dedicated NVIDIA/AMD tools detected." >> "$HW_REPORT"
        fi

        echo "" >> "$HW_REPORT"
        echo "[Disk Temperatures]" >> "$HW_REPORT"
        if command -v hddtemp >/dev/null 2>&1; then
            hddtemp /dev/sd* /dev/nvme* 2>/dev/null >> "$HW_REPORT"
        elif command -v smartctl >/dev/null 2>&1; then
            for disk in $(lsblk -nd -o NAME | grep -E "^(sd|nvme)"); do
                TEMP=$(smartctl -A "/dev/$disk" 2>/dev/null | grep -iE "Temperature_Celsius|Temperature:|Temperature Sensor" | awk '{print $NF}' | head -n 1)
                if [ -n "$TEMP" ]; then
                    echo "/dev/$disk: ${TEMP}°C" >> "$HW_REPORT"
                fi
            done
        else
            echo "Please install 'hddtemp' or 'smartmontools' to read disk temperatures." >> "$HW_REPORT"
        fi
    }

    case "$HW_ACTION" in
        1) do_core ;;
        2) do_storage ;;
        3) do_thermals ;;
        4) do_core; do_storage; do_thermals ;;
    esac

    echo "============================================================" >> "$HW_REPORT"

    zenity --text-info --title="Hardware Auditor" \
        --filename="$HW_REPORT" --width=850 --height=700 \
        --font="Monospace 10" 2>/dev/null

    zenity --question --title="Export Report" \
        --text="Do you want to save this hardware report to your home folder?" 2>/dev/null

    if [ $? -eq 0 ]; then
        EXPORT_PATH="$REAL_HOME/hardware_report_$(date +%Y%m%d_%H%M%S).txt"
        cp "$HW_REPORT" "$EXPORT_PATH"
        chown "$REAL_USER:$REAL_USER" "$EXPORT_PATH"
        print_success "Hardware report exported to: $EXPORT_PATH"
        zenity --info --title="Exported" --text="Report saved at:\n$EXPORT_PATH" 2>/dev/null
    fi

    rm -f "$HW_REPORT"
}
