#!/bin/sh
####################################
#        __    ______  ______      #
#       |  |  |  ____||  ____|     #
#       |  |  | | __  | | __       #
#       |  |__| ||_ | | ||_ |      #
#       |_____|\____| |_____|      #
# -------------------------------- #
#   >> https://lucianogg.info      #
####################################
#PKG-CONFIGS: ENDLESSH(endlessh.sh)#
####################################

configure_endlessh() 
{
    PORT="$1"
    SSH_PORT="$2"
    CONFIG_DIR="/etc/endlessh"
    CONFIG_FILE="$CONFIG_DIR/config"

    if [ -n "$SSH_PORT" ]; then
        print_info "Moving real SSH service to port $SSH_PORT..."
        sed -i -E "s/^#?Port [0-9]+/Port $SSH_PORT/" /etc/ssh/sshd_config
        
        if systemctl is-active --quiet sshd; then
            systemctl restart sshd
        elif systemctl is-active --quiet ssh; then
            systemctl restart ssh
        fi
        print_success "Real SSH port successfully moved to $SSH_PORT."
    fi

    mkdir -p "$CONFIG_DIR"

    print_info "Writing Endlessh configurations to $CONFIG_FILE..."
    cat <<EOF > "$CONFIG_FILE"
# Generated by Linux Master Assistant
Port $PORT
Delay 10000
MaxLineLength 32
MaxClients 4096
LogLevel 1
BindFamily 0
EOF

    # If the user selected a port below 1024 (like 22), Endlessh needs capabilities
    # to bind to privileged ports since it runs as an unprivileged user.
    if [ "$PORT" -le 1024 ]; then
        print_warning "Port $PORT is privileged. Granting CAP_NET_BIND_SERVICE to endlessh."
        mkdir -p /etc/systemd/system/endlessh.service.d/
        cat <<EOF > /etc/systemd/system/endlessh.service.d/override.conf
[Service]
AmbientCapabilities=CAP_NET_BIND_SERVICE
PrivateUsers=false
EOF
        systemctl daemon-reload
    fi

    systemctl enable endlessh 2>/dev/null
    systemctl restart endlessh 2>/dev/null
    print_success "Endlessh honeypot configured on port $PORT and activated."
}
