#!/bin/sh
####################################
#        __    ______  ______      #
#       |  |  |  ____||  ____|     #
#       |  |  | | __  | | __       #
#       |  |__| ||_ | | ||_ |      #
#       |_____|\____| |_____|      #
# -------------------------------- #
#   >> https://lucianogg.info      #
####################################
#PKG-CONFIGS: FAIL2BAN(fail2ban.sh)#
####################################

configure_fail2ban() 
{
    BANTIME="$1"
    MAXRETRY="$2"
    
    JAIL_FILE="/etc/fail2ban/jail.local"

    print_info "Configuring Fail2Ban advanced protection..."
    ACTUAL_SSH_PORT=$(grep -E "^Port [0-9]+" /etc/ssh/sshd_config | awk '{print $2}' | head -n 1)
    ACTUAL_SSH_PORT=${ACTUAL_SSH_PORT:-ssh}
    print_info "Detected real SSH running on port: $ACTUAL_SSH_PORT. Locking it down."
    print_info "Writing local jail configurations to $JAIL_FILE..."
    cat <<EOF > "$JAIL_FILE"
# =========================================================
# Generated by Linux Master Assistant
# =========================================================

[DEFAULT]
# Never ban the local loopback interface
ignoreip = 127.0.0.1/8 ::1

# Time a host is banned
bantime  = $BANTIME

# Time window during which the maxretry failures must occur
findtime  = 10m

# Number of failures before an IP gets banned
maxretry = $MAXRETRY

[sshd]
enabled = true
port    = $ACTUAL_SSH_PORT
logpath = %(sshd_log)s
backend = %(sshd_backend)s
EOF

    # 3. Apply configurations safely
    if systemctl is-active --quiet fail2ban; then
        systemctl restart fail2ban 2>/dev/null
    else
        systemctl enable --now fail2ban 2>/dev/null
    fi

    print_success "Fail2Ban is now active and protecting SSH on port $ACTUAL_SSH_PORT."
}
